create table LABELS
(
    ID   IDENTITY,
    NAME VARCHAR(50) UNIQUE
);

create table POSTS
(
    ID         IDENTITY,
    UUID       VARCHAR(50) UNIQUE,
    USER_ID    VARCHAR(50),
    TITLE      VARCHAR(200),
    LABEL_ID   NUMERIC,
    CREATED    DATETIME,
    TEXT       CLOB,
    CONSTRAINT LABEL_FK FOREIGN KEY (LABEL_ID) REFERENCES LABELS (ID)
);

create index POSTS_LABEL_IXF on POSTS (LABEL_ID);